name: CI

on:
  pull_request:
    branches:    
      - master
  push:
    branches:    
      - master

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    - name: Building the project
      run: npm run build
    - name: Unit tests
      run: npm run test
  
  load_tests:
    name: Run load tests
    runs-on: ubuntu-16.04
    needs: [build, integration_tests]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install Locust
      run: python3 -m pip install locust==1.3.1
    - name: Load tests
      run: npm run test:load
